namespace Odca.Web.Navigation;

/// <summary>
/// Registro central de navegação (decisão D-OC4): substitui as regras embutidas em
/// _Layout.cshtml. Ordem dos itens = ordem visual atual. Novos itens do Bloco B:
/// contratos-arquivados, suporte-tecnico (cliente e plataforma), minha-conta,
/// localizar-usuarios (plataforma); placeholders "Publicação e versões" e módulos de
/// biblioteca/configurações passam a apontar para páginas reais (PlatformLibrary e
/// PlatformOperations).
/// </summary>
public static class NavigationRegistry
{
    private const string GroupUppercase = "margin-top: .75rem; text-transform: uppercase;";

    private static Dictionary<string, string> T(NavContext x, params (string Key, string Value)[] extra)
    {
        var d = new Dictionary<string, string>();
        if (!string.IsNullOrEmpty(x.TenantId)) d["tenantId"] = x.TenantId;
        foreach (var (key, value) in extra) d[key] = value;
        return d;
    }

    public static IReadOnlyList<NavItem> Client(NavContext c)
    {
        bool contractsGroup(NavContext x) =>
            x.CanReadContracts || x.CanReadStudio || x.CanReadDocuments || x.CanReadDrafts || x.HasContract;
        bool tenant(NavContext x) => x.HasTenant && x.HasActiveMembership;

        return new List<NavItem>
        {
            new("inicio", "Início", "⌂", "Onboarding", "CustomerHome",
                Group: "Início", GroupStyle: "margin-top: .5rem; text-transform: uppercase;", AriaLabel: "Início",
                IsActive: x => x.Controller == "Onboarding" && x.Action == "CustomerHome"),
            new("primeiros-passos", "Primeiros passos", "→", "Onboarding", "GettingStarted",
                BuildRoute: x => T(x),
                Available: tenant,
                IsActive: x => x.Controller == "Onboarding" && x.Action == "GettingStarted"),
            new("pacientes", "Pacientes", "♙", "Patients", "Index",
                Group: "Pacientes", GroupStyle: GroupUppercase, FeatureCode: "patients",
                BuildRoute: x => T(x),
                Available: x => tenant(x) && x.CanReadPatients,
                IsActive: x => x.Controller == "Patients"),
            new("modelos-disponiveis", "Modelos disponíveis", "▤", "Studio", "Index",
                Group: "Contratos", GroupStyle: GroupUppercase, FeatureCode: "templates", AriaLabel: "Modelos disponíveis",
                BuildRoute: x => T(x),
                Available: x => tenant(x) && contractsGroup(x) && x.CanReadStudio,
                IsActive: x => x.Controller == "Studio"),
            new("meus-contratos", "Meus contratos", "📑", "Contracts", "List",
                FeatureCode: "documents", AriaLabel: "Meus contratos",
                BuildRoute: x => T(x),
                Available: x => tenant(x) && contractsGroup(x) && x.CanReadContracts,
                IsActive: x => x.Controller == "Contracts" && x.Action == "List"),
            new("minhas-minutas", "Minhas minutas", "✎", "Documents", "Index",
                FeatureCode: "contract_drafts", AriaLabel: "Minhas minutas",
                BuildRoute: x => T(x, ("stage", "draft")),
                Available: x => tenant(x) && contractsGroup(x) && (x.CanReadStudio || x.CanReadDrafts),
                IsActive: x => x.Controller == "Documents" && x.Q("stage") == "draft"),
            new("novo-contrato", "Novo contrato", "+", "Documents", "NewDocument",
                FeatureCode: "contract_drafts", AriaLabel: "Novo contrato",
                BuildRoute: x => T(x),
                Available: x => tenant(x) && contractsGroup(x) && x.CanCreateDocument,
                IsActive: x => x.Controller == "Documents" && x.Action == "NewDocument"),
            new("acervo-documentos", "Acervo de documentos", "🗂", "Documents", "Index",
                FeatureCode: "documents", AriaLabel: "Acervo de documentos",
                BuildRoute: x => T(x),
                Available: x => tenant(x) && contractsGroup(x) && x.CanReadDocuments,
                IsActive: x => x.Controller == "Documents" && x.Action != "NewDocument" && x.Q("stage") != "draft" && x.Q("stage") != "ready_for_signature"),
            new("contratos-arquivados", "Arquivados", "🗃", "Contracts", "List",
                FeatureCode: "documents", AriaLabel: "Contratos arquivados",
                BuildRoute: x => T(x, ("status", "arquivados")),
                Available: x => tenant(x) && contractsGroup(x) && x.CanReadContracts,
                IsActive: x => x.Controller == "Contracts" && x.Action == "List" && (x.Q("status") == "archived" || x.Q("status") == "arquivados")),
            new("ficha-contrato", "Ficha do contrato", "📄", "Contracts", "Sheet",
                AriaLabel: "Ficha do contrato",
                BuildRoute: x => T(x, ("contractId", x.ContractId!)),
                Available: x => tenant(x) && contractsGroup(x) && x.HasContract,
                IsActive: x => x.Controller == "Contracts" && x.Action == "Sheet"),
            new("assinaturas", "Assinaturas", "✒", "Documents", "Index",
                FeatureCode: "signatures", AriaLabel: "Assinaturas pendentes",
                BuildRoute: x => T(x, ("stage", "ready_for_signature")),
                Available: x => tenant(x) && x.CanReadDocuments,
                IsActive: x => x.Controller == "Documents" && x.Q("stage") == "ready_for_signature"),
            new("renovacoes-prazos", "Renovações e prazos", "↻", "Renewals", "Index",
                AriaLabel: "Renovações e prazos",
                BuildRoute: x => T(x),
                Available: x => tenant(x) && x.CanReadRenewals,
                IsActive: x => x.Controller == "Renewals"),
            new("solicitacoes-odca", "Solicitações ODCA", "☵", "Reviews", "Index",
                FeatureCode: "reviews",
                BuildRoute: x => T(x),
                Available: x => tenant(x) && x.CanReadReviews && !x.ReviewsPlanRestricted,
                IsActive: x => x.Controller == "Reviews"),
            new("central-solicitacoes", "Central de solicitações", "✉", "Solicitacoes", "Index",
                BuildRoute: x => T(x),
                Available: x => tenant(x) && x.CanReadSolicitations,
                IsActive: x => x.Controller == "Solicitacoes" && string.IsNullOrEmpty(x.Q("service"))),
            new("suporte-tecnico", "Suporte técnico", "✉", "Solicitacoes", "Index",
                AriaLabel: "Suporte técnico e recuperação de acesso",
                BuildRoute: x => T(x, ("service", "suporte_tecnico")),
                Available: x => tenant(x) && x.CanReadSolicitations,
                IsActive: x => x.Controller == "Solicitacoes" && x.Q("service") == "suporte_tecnico"),
            new("caixa", "Caixa", "◫", "Inbox", "Index",
                Group: "Operações", GroupStyle: GroupUppercase, AriaLabel: "Caixa operacional",
                BuildRoute: x => T(x),
                Available: x => tenant(x) && (x.CanAccessWorkspace || x.CanReadObligations) && x.CanAccessWorkspace,
                IsActive: x => x.Controller == "Inbox"),
            new("agenda", "Agenda", "▦", "Agenda", "Index",
                AriaLabel: "Agenda mensal",
                BuildRoute: x => T(x),
                Available: x => tenant(x) && (x.CanAccessWorkspace || x.CanReadObligations) && x.CanAccessWorkspace,
                IsActive: x => x.Controller == "Agenda"),
            new("obrigacoes", "Obrigações", "✓", "Obligations", "Index",
                AriaLabel: "Central de obrigações",
                BuildRoute: x => T(x),
                Available: x => tenant(x) && (x.CanAccessWorkspace || x.CanReadObligations) && x.CanReadObligations,
                IsActive: x => x.Controller == "Obligations"),
            new("filtros-salvos", "Filtros salvos", "☆", "Obligations", "Index",
                Fragment: "saved-views",
                BuildRoute: x => T(x),
                Available: x => tenant(x) && (x.CanAccessWorkspace || x.CanReadObligations) && x.CanReadObligations),
            new("equipe-permissoes", "Equipe e permissões", "◎", "Organizations", "Team",
                AriaLabel: "Equipe e permissões",
                BuildRoute: x => T(x),
                Available: x => tenant(x) && x.CanReadOrganization,
                IsActive: x => x.Controller == "Organizations" && x.Action == "Team"),
            new("organizacao", "Organização", "⚙", "Organizations", "Edit",
                Group: "Minha organização e plano", GroupStyle: GroupUppercase, AriaLabel: "Configurações da organização",
                BuildRoute: x => T(x),
                Available: x => tenant(x) && x.CanReadOrganization,
                IsActive: x => x.Controller == "Organizations" && x.Action == "Edit"),
            new("plano-consumo", "Plano e consumo", "◫", "Consumption", "Index",
                BuildRoute: x => T(x),
                Available: x => tenant(x) && x.CanReadOrganization,
                IsActive: x => x.Controller == "Consumption"),
            new("auditoria-organizacao", "Auditoria", "☰", "Consumption", "Index",
                Fragment: "historico",
                BuildRoute: x => T(x),
                Available: x => tenant(x) && x.CanReadOrganization),
            new("minha-conta", "Minha conta", "👤", "Account", "Conta",
                AriaLabel: "Minha conta",
                Available: _ => true,
                IsActive: x => x.Controller == "Account" && x.Action == "Conta"),
            new("notificacoes", "Notificações", "🔔", "Account", "Notifications",
                AriaLabel: "Notificações",
                Available: x => x.HasTenant,
                IsActive: x => x.Controller == "Account" && x.Action == "Notifications"),
            new("ajuda", "Ajuda e como usar", "?", "Modules", "Index",
                Group: "Suporte", GroupStyle: GroupUppercase,
                BuildRoute: x => T(x, ("module", "ajuda"))),
            new("privacidade", "Privacidade", "◇", "Privacy", "Index",
                AriaLabel: "Privacidade"),
        };
    }

    public static IReadOnlyList<NavItem> Platform(NavContext c)
    {
        bool tenant(NavContext x) => x.HasTenant;

        return new List<NavItem>
        {
            new("visao-global", "Visão global", "⌂", "Home", "Index",
                Group: "Plataforma MNSOFT", AriaLabel: "Visão global",
                IsActive: x => x.Controller == "Home"),
            new("organizacoes", "Organizações", "◎", "Organizations", "Index",
                IsActive: x => x.Controller == "Organizations" && string.IsNullOrWhiteSpace(x.ActiveTenantId)),
            new("usuarios-acessos", "Usuários e acessos", "▣", "Customers", "Index",
                AriaLabel: "Usuários e acessos",
                IsActive: x => x.Controller == "Customers" && x.Action != "Users"),
            new("localizar-usuarios", "Localizar usuários", "⌕", "Customers", "Users",
                AriaLabel: "Busca global de usuários",
                IsActive: x => x.Controller == "Customers" && x.Action == "Users"),
            new("planos-modulos", "Planos e módulos", "▦", "Plans", "Index",
                AriaLabel: "Planos e módulos",
                IsActive: x => x.Controller == "Plans"),
            new("biblioteca-modelos", "Biblioteca de modelos", "▤", "PlatformLibrary", "Index",
                AriaLabel: "Biblioteca de modelos",
                IsActive: x => x.Controller == "PlatformLibrary"),
            new("solicitacoes-sla", "Solicitações e SLA", "☵", "AdminSolicitacoes", "Index",
                AriaLabel: "Fila de solicitações e SLA",
                IsActive: x => x.Controller == "AdminSolicitacoes" && x.Action != "Aprovacoes"),
            new("aprovacao-modelos", "Aprovação de modelos", "✒", "AdminSolicitacoes", "Aprovacoes",
                AriaLabel: "Aprovação de modelos oficiais",
                IsActive: x => x.Controller == "AdminSolicitacoes" && x.Action == "Aprovacoes"),
            new("auditoria-plataforma", "Auditoria", "☰", "PlatformAudit", "Index",
                AriaLabel: "Auditoria da plataforma",
                IsActive: x => x.Controller == "PlatformAudit"),
            new("configuracoes-operacionais", "Configurações operacionais", "⚙", "PlatformOperations", "Index",
                AriaLabel: "Configurações operacionais",
                IsActive: x => x.Controller == "PlatformOperations"),
            new("caixa", "Caixa", "◫", "Inbox", "Index",
                AriaLabel: "Caixa operacional",
                BuildRoute: x => T(x),
                Available: x => tenant(x) && x.CanAccessWorkspace,
                IsActive: x => x.Controller == "Inbox"),
            new("agenda", "Agenda", "▦", "Agenda", "Index",
                AriaLabel: "Agenda mensal",
                BuildRoute: x => T(x),
                Available: x => tenant(x) && x.CanAccessWorkspace,
                IsActive: x => x.Controller == "Agenda"),
            new("obrigacoes", "Obrigações", "✓", "Obligations", "Index",
                AriaLabel: "Central de obrigações",
                BuildRoute: x => T(x),
                Available: x => tenant(x) && x.CanReadObligations,
                IsActive: x => x.Controller == "Obligations"),
            new("renovacoes-prazos", "Renovações e prazos", "↻", "Renewals", "Index",
                AriaLabel: "Central de renovações e prazos",
                BuildRoute: x => T(x),
                Available: x => tenant(x) && x.CanReadRenewals,
                IsActive: x => x.Controller == "Renewals"),
            new("acervo-documentos", "Acervo", "🗂", "Documents", "Index",
                FeatureCode: "documents", AriaLabel: "Acervo de documentos",
                BuildRoute: x => T(x),
                Available: x => tenant(x) && x.CanReadDocuments,
                IsActive: x => x.Controller == "Documents" && x.Action != "NewDocument" && x.Q("stage") != "draft" && x.Q("stage") != "ready_for_signature"),
            new("assinaturas", "Assinaturas", "✒", "Documents", "Index",
                FeatureCode: "signatures", AriaLabel: "Assinaturas pendentes",
                BuildRoute: x => T(x, ("stage", "ready_for_signature")),
                Available: x => tenant(x) && x.CanReadDocuments,
                IsActive: x => x.Controller == "Documents" && x.Q("stage") == "ready_for_signature"),
            new("modelos", "Modelos", "▤", "Studio", "Index",
                FeatureCode: "templates", AriaLabel: "Modelos de documento",
                BuildRoute: x => T(x),
                Available: x => tenant(x) && x.CanReadStudio,
                IsActive: x => x.Controller == "Studio"),
            new("minhas-minutas", "Minhas minutas", "✎", "Documents", "Index",
                FeatureCode: "contract_drafts", AriaLabel: "Minhas minutas",
                BuildRoute: x => T(x, ("stage", "draft")),
                Available: x => tenant(x) && x.CanReadStudio,
                IsActive: x => x.Controller == "Documents" && x.Q("stage") == "draft"),
            new("criar-documento", "Criar documento", "+", "Documents", "NewDocument",
                FeatureCode: "contract_drafts", AriaLabel: "Criar documento",
                BuildRoute: x => T(x),
                Available: x => tenant(x) && x.CanCreateDocument,
                IsActive: x => x.Controller == "Documents" && x.Action == "NewDocument"),
            new("pacientes", "Pacientes", "♙", "Patients", "Index",
                FeatureCode: "patients",
                BuildRoute: x => T(x),
                Available: x => tenant(x) && x.CanReadPatients,
                IsActive: x => x.Controller == "Patients"),
            new("solicitacoes-odca", "Solicitações ODCA", "☵", "Reviews", "Index",
                FeatureCode: "reviews",
                BuildRoute: x => T(x),
                Available: x => tenant(x) && x.CanReadReviews && !x.ReviewsPlanRestricted,
                IsActive: x => x.Controller == "Reviews"),
            new("central-solicitacoes", "Central de solicitações", "✉", "Solicitacoes", "Index",
                BuildRoute: x => T(x),
                Available: x => tenant(x) && x.CanReadSolicitations,
                IsActive: x => x.Controller == "Solicitacoes" && string.IsNullOrEmpty(x.Q("service"))),
            new("suporte-tecnico", "Suporte técnico", "✉", "Solicitacoes", "Index",
                AriaLabel: "Suporte técnico e recuperação de acesso",
                BuildRoute: x => T(x, ("service", "suporte_tecnico")),
                Available: x => tenant(x) && x.CanReadSolicitations,
                IsActive: x => x.Controller == "Solicitacoes" && x.Q("service") == "suporte_tecnico"),
            new("ficha-contrato", "Ficha", "📄", "Contracts", "Sheet",
                AriaLabel: "Ficha do contrato",
                BuildRoute: x => T(x, ("contractId", x.ContractId!)),
                Available: x => tenant(x) && x.HasContract,
                IsActive: x => x.Controller == "Contracts"),
            new("equipe-permissoes", "Equipe e permissões", "◎", "Organizations", "Team",
                AriaLabel: "Equipe e permissões",
                BuildRoute: x => T(x),
                Available: x => tenant(x) && x.CanReadOrganization,
                IsActive: x => x.Controller == "Organizations" && x.Action == "Team"),
            new("configuracoes-org", "Configurações", "⚙", "Organizations", "Edit",
                AriaLabel: "Configurações da organização",
                BuildRoute: x => T(x),
                Available: x => tenant(x) && x.CanReadOrganization,
                IsActive: x => x.Controller == "Organizations" && x.Action == "Edit"),
            new("plano-consumo", "Plano e consumo", "◫", "Consumption", "Index",
                BuildRoute: x => T(x),
                Available: x => tenant(x) && x.CanReadOrganization,
                IsActive: x => x.Controller == "Consumption"),
            new("auditoria-organizacao", "Auditoria", "☰", "Consumption", "Index",
                Fragment: "historico",
                BuildRoute: x => T(x),
                Available: x => tenant(x) && x.CanReadOrganization),
            new("privacidade", "Privacidade", "◇", "Privacy", "Index",
                AriaLabel: "Privacidade"),
        };
    }
}
